[package]
name = "blazesym"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "blazesym"
crate-type = ["cdylib", "rlib", "staticlib"]

[dependencies]
nix = "0.24.1"
regex = "*"

[build-dependencies]
cbindgen = "*"

[features]
cheader = []
